### ISSUE TITLE
Please update wiki, how to use @angular/service-worker 5.0.0

### ISSUE THREAD

**Issue by sourajitpwc** [angular/service-worker-builds#1]
It has been found that, few days back you have updated @angular/service-worker 5.0.0. Currently there is no worker-basic.js. 
With in @angular/service-worker package I am getting ServiceWorkerModule.

import {ServiceWorkerModule} from '@angular/service-worker';
I have also injected this module. 

At the time of ng serve or ng build I am getting below error.

```
ERROR in Error: Metadata version mismatch for module C:/projects/angular2/Demo-PWA-ng4/node_modules/@angular/service-worker/service-worker.d.ts, found version 4, expecte
 3, resolving symbol AppModule in C:/projects/angular2/Demo-PWA-ng4/src/app/app.module.ts, resolving symbol AppModule in C:/projects/angular2/Demo-PWA-ng4/src/app/app.mo
ule.ts
    at Error (native)
    at syntaxError (C:\projects\angular2\Demo-PWA-ng4\node_modules\@angular\compiler\bundles\compiler.umd.js:1729:34)
    at simplifyInContext (C:\projects\angular2\Demo-PWA-ng4\node_modules\@angular\compiler\bundles\compiler.umd.js:24979:23)
    at StaticReflector.simplify (C:\projects\angular2\Demo-PWA-ng4\node_modules\@angular\compiler\bundles\compiler.umd.js:24991:13)
    at StaticReflector.annotations (C:\projects\angular2\Demo-PWA-ng4\node_modules\@angular\compiler\bundles\compiler.umd.js:24418:41)
    at _getNgModuleMetadata (C:\projects\angular2\Demo-PWA-ng4\node_modules\@angular\compiler-cli\src\ngtools_impl.js:138:31)
    at _extractLazyRoutesFromStaticModule (C:\projects\angular2\Demo-PWA-ng4\node_modules\@angular\compiler-cli\src\ngtools_impl.js:109:26)
    at Object.listLazyRoutesOfModule (C:\projects\angular2\Demo-PWA-ng4\node_modules\@angular\compiler-cli\src\ngtools_impl.js:53:22)
    at Function.NgTools_InternalApi_NG_2.listLazyRoutes (C:\projects\angular2\Demo-PWA-ng4\node_modules\@angular\compiler-cli\src\ngtools_api.js:91:39)
    at AotPlugin._getLazyRoutesFromNgtools (C:\projects\angular2\Demo-PWA-ng4\node_modules\@ngtools\webpack\src\plugin.js:212:44)
    at _donePromise.Promise.resolve.then.then.then.then.then (C:\projects\angular2\Demo-PWA-ng4\node_modules\@ngtools\webpack\src\plugin.js:448:24)
    at process._tickCallback (internal/process/next_tick.js:109:7)
```
It is also found that editor also throwing **rviceWorkerModule** not found.

Please suggest me what do now.

Thanks in advance.

**Comment by sourajitpwc** [comment]
Any update??

**Comment by jasonaden** [comment]
@sourajitpwc Please move this issue into the https://github.com/angular/angular/issues repo. This `builds` repo is only for publishing. We don't monitor issues here.
